### ISSUE TITLE
Plugin errors on start

### ISSUE THREAD

**Issue by AverageFemale** [GamerCoder215/StarCosmetics#12] opened 2022-12-19 21:16 UTC
### Bug Type

Console Errors

### Minecraft Version

1.18.2

### Description

The plugin fails to startup. Don't know what other way to put this.

### Expected Behavior

Plugin doesn't load up, causing it to be disabled.

### Actual Behavior

Plugin loads up, causing it to be enabled.

### Other Information

`[17:10:34] [Server thread/ERROR]: Error occurred while enabling StarCosmetics v1.0.0 (Is it up to date?)
me.gamercoder215.starcosmetics.api.cosmetics.structure.MalformedStructureException: Unknown Material 'REINFORCED_DEEPSLATE'
	at me.gamercoder215.starcosmetics.api.cosmetics.structure.ModernStructureReader.read(ModernStructureReader.java:140) ~[StarCosmetics-1.0.0.jar:?]
	at me.gamercoder215.starcosmetics.StarCosmetics.getAvailableStructures(StarCosmetics.java:393) ~[StarCosmetics-1.0.0.jar:?]
	at me.gamercoder215.starcosmetics.StarCosmetics.onEnable(StarCosmetics.java:120) ~[StarCosmetics-1.0.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-372]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-372]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-372]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-372]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-372]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-372]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-372]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by GamerCoder215** [comment] 2022-12-19 22:03
Can confirm this happens on 1.18.2 (and earlier versions). Will implement and test for a fix later.

**Comment by GamerCoder215** [comment] 2022-12-21 00:55
Will test the fixes made in [`94d788`](https://github.com/GamerCoder215/StarCosmetics/commit/94d7889aa2f6bbd7912860573d1799b7089e35bd) when I get home.

As for an explanation, this should be provided by the API:
```
Structures will not be read properly and will throw errors if they are read on an incompatible version, making this method obselete.
```

I forgot that the reader will throw errors if it doesn't recognize material names in the structure files. Technically `REINFORCED_DEEPSLATE` doesn't exist on 1.18.2 and earlier versions, which is why it works on 1.19 and above.

This fix checks the minimum version before this reading happens, making sure that the structure doesn't show up on 1.18.2 and earlier (what it was intended to do).

**Comment by GamerCoder215** [comment] 2022-12-22 19:01
v1.0.1 runs properly on 1.18.2.

Will release later today. Marking as closed and fixed.

**Closed by GamerCoder215** 2022-12-22 19:01 UTC
Labels: bug
